spring:


  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 20MB
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/TobeHonest
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tobehonest?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: passw123

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        # show_sql: true
        #format_sql: true
        #전부
        default_lazy_behavior: proxy

  jwt:
    secret:  c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  data:
    redis:
      host: localhost
      port: 6379

#절 ~ 때 깃허브에 안올리지
cloud:
  aws:
    s3:
      bucket: tobehonest
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      accessKey: AKIAYJC6YAT3SCVMUU56
      secretKey: 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
logging.level:
  org.hibernate.SQL: error
  org.hibernate.orm.jdbc.bind: error #스프링 부트 3.x, hibernate6